# SPX 2010-2013

In [12]:
import pandas as pd

df = pd.read_csv('combined_options_data.csv')
df.head()

,QUOTE_UNIXTIME,QUOTE_READTIME,QUOTE_DATE,QUOTE_TIME_HOURS,UNDERLYING_LAST,EXPIRE_DATE,EXPIRE_UNIX,DTE,C_DELTA,C_GAMMA,...,P_SIZE,P_LAST,P_DELTA,P_GAMMA,P_VEGA,P_THETA,P_RHO,P_IV,P_VOLUME,STRIKE_DISTANCE
0,1262638800,04-01-2010 16:00,04-01-2010,16,1132.99,07-01-2010,1262898000,3.0,1.0,0.0,...,0 x 420,0.05,-0.00077,0.00004,0.00439,-0.02116,-0.00049,0.64013,550.0,208.0
1,1262638800,04-01-2010 16:00,04-01-2010,16,1132.99,07-01-2010,1262898000,3.0,1.0,0.0,...,0 x 455,0.05,-0.00203,0.00006,0.00911,-0.04056,0.00000,0.59859,NaN,183.0
2,1262638800,04-01-2010 16:00,04-01-2010,16,1132.99,07-01-2010,1262898000,3.0,1.0,0.0,...,717 x 177,0.10,-0.00369,0.00022,0.01302,-0.05898,-0.00071,0.53885,NaN,158.0
3,1262638800,04-01-2010 16:00,04-01-2010,16,1132.99,07-01-2010,1262898000,3.0,1.0,0.0,...,470 x 98,0.15,-0.00894,0.00038,0.02786,-0.12758,-0.00086,0.50273,NaN,133.0
4,1262638800,04-01-2010 16:00,04-01-2010,16,1132.99,07-01-2010,1262898000,3.0,1.0,0.0,...,428 x 63,0.20,-0.01251,0.00066,0.03857,-0.15692,-0.00147,0.42725,720.0,108.0

In [7]:
print("Min QUOTE_DATE:", df["QUOTE_DATE"].min())
print("Max QUOTE_DATE:", df["QUOTE_DATE"].max())

Min QUOTE_DATE: 01-02-2010
Max QUOTE_DATE: 31-12-2012

In [3]:
len(df)

1048531

# FOREX 9/9/2025

In [14]:
fx = pd.read_csv('forex_data_2020-2025.csv')
fx.head()

       Date     Close      High       Low      Open currency_pair
0  1/1/2020  1.122083  1.122838  1.115947  1.122083       EUR/USD
1  1/2/2020  1.122083  1.122712  1.116682  1.121894       EUR/USD
2  1/3/2020  1.117144  1.118068  1.112570  1.117081       EUR/USD
3  1/6/2020  1.116196  1.120825  1.115810  1.116246       EUR/USD
4  1/7/2020  1.119799  1.119946  1.113487  1.119583       EUR/USD

# AAPL

In [19]:
aapl = pd.read_csv('aapl_2021_2023.csv')
aapl.head()

C:\Users\aicha\AppData\Local\Temp\ipykernel_5372\1781982939.py:1: DtypeWarning: Columns (0:  [C_LAST], 1:  [C_BID], 2:  [C_ASK], 3:  [P_BID], 4:  [P_ASK], 5:  [P_LAST]) have mixed types. Specify dtype option on import or set low_memory=False.
  aapl = pd.read_csv('aapl_2021_2023.csv')

,[QUOTE_UNIXTIME],[QUOTE_READTIME],[QUOTE_DATE],[QUOTE_TIME_HOURS],[UNDERLYING_LAST],[EXPIRE_DATE],[EXPIRE_UNIX],[DTE],[C_DELTA],[C_GAMMA],...,[P_LAST],[P_DELTA],[P_GAMMA],[P_VEGA],[P_THETA],[P_RHO],[P_IV],[P_VOLUME],[STRIKE_DISTANCE],[STRIKE_DISTANCE_PCT]
0,1656705600,2022-07-01 16:00,2022-07-01,16.0,138.9,2022-07-01,1656705600,0.0,1.00000,0.00000,...,0.020000,-0.00093,0.00004,0.00011,-0.00547,0.0,4.889460,0.000000,68.9,0.496
1,1656705600,2022-07-01 16:00,2022-07-01,16.0,138.9,2022-07-01,1656705600,0.0,1.00000,0.00000,...,0.010000,-0.00066,0.00001,0.00061,-0.00491,0.0,4.422080,0.000000,63.9,0.460
2,1656705600,2022-07-01 16:00,2022-07-01,16.0,138.9,2022-07-01,1656705600,0.0,1.00000,0.00000,...,0.010000,-0.00108,0.00009,-0.00012,-0.00455,0.0,3.984220,0.000000,58.9,0.424
3,1656705600,2022-07-01 16:00,2022-07-01,16.0,138.9,2022-07-01,1656705600,0.0,1.00000,0.00000,...,0.010000,-0.00100,0.00015,-0.00018,-0.00525,0.0,3.571790,0.000000,53.9,0.388
4,1656705600,2022-07-01 16:00,2022-07-01,16.0,138.9,2022-07-01,1656705600,0.0,0.99404,0.00067,...,0.010000,-0.00138,0.00014,0.00025,-0.00453,0.0,3.180820,0.000000,48.9,0.352

In [24]:
print("Before:", aapl.columns.tolist())

aapl.columns = aapl.columns.str.strip().str.replace(r"[\[\]]", "", regex=True)

print("After:", aapl.columns.tolist())

aapl["QUOTE_DATE"] = pd.to_datetime(aapl["QUOTE_DATE"], errors="coerce")
print(aapl["QUOTE_DATE"].dropna().sort_values().drop_duplicates().tail(20))

Before: ['[QUOTE_UNIXTIME]', ' [QUOTE_READTIME]', ' [QUOTE_DATE]', ' [QUOTE_TIME_HOURS]', ' [UNDERLYING_LAST]', ' [EXPIRE_DATE]', ' [EXPIRE_UNIX]', ' [DTE]', ' [C_DELTA]', ' [C_GAMMA]', ' [C_VEGA]', ' [C_THETA]', ' [C_RHO]', ' [C_IV]', ' [C_VOLUME]', ' [C_LAST]', ' [C_SIZE]', ' [C_BID]', ' [C_ASK]', ' [STRIKE]', ' [P_BID]', ' [P_ASK]', ' [P_SIZE]', ' [P_LAST]', ' [P_DELTA]', ' [P_GAMMA]', ' [P_VEGA]', ' [P_THETA]', ' [P_RHO]', ' [P_IV]', ' [P_VOLUME]', ' [STRIKE_DISTANCE]', ' [STRIKE_DISTANCE_PCT]']
After: ['QUOTE_UNIXTIME', 'QUOTE_READTIME', 'QUOTE_DATE', 'QUOTE_TIME_HOURS', 'UNDERLYING_LAST', 'EXPIRE_DATE', 'EXPIRE_UNIX', 'DTE', 'C_DELTA', 'C_GAMMA', 'C_VEGA', 'C_THETA', 'C_RHO', 'C_IV', 'C_VOLUME', 'C_LAST', 'C_SIZE', 'C_BID', 'C_ASK', 'STRIKE', 'P_BID', 'P_ASK', 'P_SIZE', 'P_LAST', 'P_DELTA', 'P_GAMMA', 'P_VEGA', 'P_THETA', 'P_RHO', 'P_IV', 'P_VOLUME', 'STRIKE_DISTANCE', 'STRIKE_DISTANCE_PCT']
359297   2023-03-06
360402   2023-03-07
361540   2023-03-08
362715   2023-03-09
363923   2023-03-10
365127   2023-03-13
366198   2023-03-14
366833   2023-03-15
368700   2023-03-16
369322   2023-03-17
370765   2023-03-20
371891   2023-03-21
373033   2023-03-22
374195   2023-03-23
375388   2023-03-24
376547   2023-03-27
377682   2023-03-28
378812   2023-03-29
379971   2023-03-30
381205   2023-03-31
Name: QUOTE_DATE, dtype: datetime64[us]